<?php

namespace AppBundle\Repository;

/**
 * CompagnieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnieRepository extends \Doctrine\ORM\EntityRepository
{
}
