<?php

namespace AppBundle\Repository;

/**
 * ComptoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComptoirRepository extends \Doctrine\ORM\EntityRepository
{
}
