<?php

namespace AppBundle\Repository;

/**
 * PorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PorteRepository extends \Doctrine\ORM\EntityRepository
{
}
