<?php

namespace AppBundle\Repository;

/**
 * ProgrammePorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammePorteRepository extends \Doctrine\ORM\EntityRepository
{
}
