<?php

namespace AppBundle\Repository;

/**
 * ProgrammeComptoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgrammeComptoirRepository extends \Doctrine\ORM\EntityRepository
{
}
