<?php

namespace AppBundle\Repository;

/**
 * VolsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolsRepository extends \Doctrine\ORM\EntityRepository
{
}
